on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: run lanzouyunapi
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP environment         
      uses: nanasess/setup-php@v4.0.2
      with:
        php-version: '8.3'
    - name: Test api
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        scoop install lsd
        scoop install tre-command
        pwd
        php lanzouyunapi.php
    - name: Get Install Source
      shell: bash
      run: |
        git clone  https://github.com/lsq/install-php.git
        cd install-php
        pwd
        lsd
    - name: Setup IIS
      shell: powershell
      run: |
        
        pwd
        lsd
        cd install-php
        pwd
        lsd
        .\Install-PHP.ps1 -bldPkg .\BuildPackages\Build7.4x64Win2019.zip
        tre .
        
        
