on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: run lanzouyunapi
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    #- name: Setup PHP environment         
    #  uses: nanasess/setup-php@v4
    #  with:
    #    php-version: '8.3'
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, curl, apcu
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug
        tools: php-cs-fixer, phpunit
    
    - name: Test api
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        scoop install lsd
        scoop install tre-command
        scoop install sed
        echo "$(Resolve-Path "~/scoop/shims")" >> $GITHUB_PATH
        pwd
        php lanzouyunapi.php
        #php .\lanzouyunapi.php?data=b0ufru1i
    - name: Get Install Source
      shell: bash
      run: |
        git clone  https://github.com/lsq/install-php.git
        cd install-php
        which curl
        pwd
        ls
    - name: Setup IIS
      shell: powershell
      run: |
        Set-Item -Path Env:\Path -Value "$(Resolve-Path "~/scoop/shims");$env:Path"
        Set-Item -Path Env:\Path -Value "c:\msys64\usr\bin;$env:Path"
        echo "$env:PATH"
        which php        
        pwd
        lsd c:\tools\php
        tre c:\tools\php        
        cd install-php
        sed -i '295s/.*/echo "$env:PATH"/' Install-PHP.ps1
        sed -n '295p' Install-PHP.ps1
        sed -i '720s/-eq \(\$xml.info.vc_redist_x64.display_name\)/-like \"\*\$(((\1 -replace \$xml.info.server.supported_version, \x272022\x27) -replace \x27 - [\\\d\.]+\x27,\x27\x27))\*\"/' Install-PHP.ps1
        sed -i '721a\ Write-Output \"\$((\$reg.OpenSubKey($key + \"\\\\\\\\\" + \$subKey).getvalue(\"DisplayName\")) -replace \",\",\";\")\"' Install-PHP.ps1
        sed -n '720,722p' Install-PHP.ps1
        pwd
        lsd
        #powershell .\Install-PHP.ps1 -bldPkg .\BuildPackages\Build7.4x64Win2019.zip        
        tre .
        #(curl http://localhost/php/index.php).content      
    - name: Setup Lanzouyun api
      shell: powershell
      run: |
        Set-Item -Path Env:\Path -Value "$(Resolve-Path "~/scoop/shims");$env:Path"
        Set-Item -Path Env:\Path -Value "c:\msys64\usr\bin;$env:Path"
        powershell .\install-lanzouyun-api.ps1  .\Config.xml
        curl.exe 'http://localhost/php/lanzouyunapi.php?data=https://www.lanzouo.com/b0ufru1i'
        curl.exe 'https://vercel-chi-kohl.vercel.app/lanzouyunapi.php?data=b0ufru1i'
        #7z a -mx9 ".\php-8.3-nts-x64.zip" c:\tools\php
        tre C:\WebData
    #- uses: actions/upload-artifact@v4
    #  with:
    #    name: php.zip
    #    path: php-8.3-nts-x64.zip
        
        
        
